version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-web
    volumes:
      - ./src/app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql-5dmat-web
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web
    volumes:
      - ./src/app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src/app:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  npm:
    image: node:latest
    container_name: npm
    volumes:
      - ./src/app:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: homestead
    networks:
      - laravel